// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RRHH.Infraestructura.Data;

#nullable disable

namespace RRHH.Migrations
{
    [DbContext(typeof(RRHH_DBContext))]
    [Migration("20251124001319_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RRHH.Core.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartamentoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartamentoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("RRHH.Core.Models.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmailId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmailId");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("RRHH.Core.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpleadoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("RRHH.Core.Models.EmpleadoCurriculum", b =>
                {
                    b.Property<int>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CurriculumId"));

                    b.Property<string>("Cod_Emp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("date");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CurriculumId");

                    b.HasIndex("Cod_Emp")
                        .IsUnique();

                    b.ToTable("EmpleadoCurriculums");
                });

            modelBuilder.Entity("RRHH.Core.Models.Historial", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Codigo_Dep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo_Emp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo_Puesto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<int>("PuestoId")
                        .HasColumnType("integer");

                    b.HasKey("EmpleadoId", "DepartamentoId", "FechaInicio");

                    b.HasIndex("EmpleadoId", "PuestoId", "DepartamentoId", "FechaInicio")
                        .IsUnique();

                    b.ToTable("HistorialDepartamentos");
                });

            modelBuilder.Entity("RRHH.Core.Models.Nomina", b =>
                {
                    b.Property<int>("NominaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NominaId"));

                    b.Property<decimal>("Bonos")
                        .HasColumnType("numeric");

                    b.Property<string>("Cod_Emp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cod_Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Descuentos")
                        .HasColumnType("numeric");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PeriodoFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("date");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("numeric");

                    b.HasKey("NominaId");

                    b.HasIndex("EmpleadoId", "PeriodoInicio", "PeriodoFin")
                        .IsUnique();

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("RRHH.Core.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonaId"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonaId");

                    b.HasIndex("CI")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("RRHH.Core.Models.PersonaEmail", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<int>("EmailId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date");

                    b.HasKey("PersonaId", "EmailId", "FechaInicio");

                    b.HasIndex("EmailId");

                    b.HasIndex("PersonaId", "EmailId", "FechaInicio")
                        .IsUnique();

                    b.ToTable("PersonaEmails");
                });

            modelBuilder.Entity("RRHH.Core.Models.PersonaTelefono", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<int>("TelefonoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date");

                    b.HasKey("PersonaId", "TelefonoId", "FechaInicio");

                    b.HasIndex("TelefonoId");

                    b.HasIndex("PersonaId", "TelefonoId", "FechaInicio")
                        .IsUnique();

                    b.ToTable("PersonaTelefonos");
                });

            modelBuilder.Entity("RRHH.Core.Models.Puesto", b =>
                {
                    b.Property<int>("PuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PuestoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("PuestoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("RRHH.Core.Models.ReporteEmpleado", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReporteId"));

                    b.Property<string>("Cod_Dep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cod_Emp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartamentoEmisorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoReportadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReporteId");

                    b.HasIndex("EmpleadoReportadoId", "DepartamentoEmisorId", "Fecha")
                        .IsUnique();

                    b.ToTable("ReportesEmpleados");
                });

            modelBuilder.Entity("RRHH.Core.Models.Telefono", b =>
                {
                    b.Property<int>("TelefonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TelefonoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TelefonoId");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("RRHH.Core.Models.Views.EmpleadosActivosView", b =>
                {
                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("EmpleadosActivosViews");
                });

            modelBuilder.Entity("RRHH.Core.Models.Views.EmpleadosSalariosPuestosView", b =>
                {
                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("numeric");

                    b.ToTable("EmpleadosSalariosPuestosViews");
                });

            modelBuilder.Entity("RRHH.Core.Models.Views.HistorialDepartamentosView", b =>
                {
                    b.Property<string>("CodigoDepartamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoPuesto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("HistorialDepartamentosViews");
                });

            modelBuilder.Entity("RRHH.Core.Models.Views.ReportesEmpleadosView", b =>
                {
                    b.Property<string>("CodigoDepartamentoEmisor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoEmpleadoReportado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoReporte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("ReporteId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("ReportesEmpleadosViews");
                });

            modelBuilder.Entity("RRHH.Core.Models.Views.ResumenNominaEmpleadoView", b =>
                {
                    b.Property<decimal>("Bonos")
                        .HasColumnType("numeric");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Descuentos")
                        .HasColumnType("numeric");

                    b.Property<string>("EstadoNomina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<int>("NominaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PeriodoFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("date");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("numeric");

                    b.ToTable("ResumenNominaEmpleadoViews");
                });

            modelBuilder.Entity("RRHH.Core.Models.Empleado", b =>
                {
                    b.HasOne("RRHH.Core.Models.Persona", "Persona")
                        .WithOne("Empleado")
                        .HasForeignKey("RRHH.Core.Models.Empleado", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("RRHH.Core.Models.PersonaEmail", b =>
                {
                    b.HasOne("RRHH.Core.Models.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRHH.Core.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("RRHH.Core.Models.PersonaTelefono", b =>
                {
                    b.HasOne("RRHH.Core.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRHH.Core.Models.Telefono", "Telefono")
                        .WithMany()
                        .HasForeignKey("TelefonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Telefono");
                });

            modelBuilder.Entity("RRHH.Core.Models.Persona", b =>
                {
                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
